swan_AmazonFiles/objects/swan_AmazonFile__c/swan_AmazonFile__c.object-meta.xml
<CustomObject>
    <label>Amazon File</label>
    <nameField>
        <label>Amazon File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amazon Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

swan_AmazonFiles/objects/swan_AmazonFile__c/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

swan_AmazonFiles/objects/swan_AmazonFile__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

swan_AmazonFiles/objects/swan_AmazonFile__c/fields/MIME__c.field-meta.xml
<CustomField>
    <fullName>MIME__c</fullName>
    <label>MIME</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

swan_AmazonFiles/objects/swan_AmazonFile__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <type>TextArea</type>
</CustomField>

swan_AmazonFiles/objects/swan_AmazonFile__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

swan_AmazonFiles/objects/swan_AmazonFile__c/fields/UploadedById__c.field-meta.xml
<CustomField>
    <fullName>UploadedById__c</fullName>
    <label>Uploaded By Id</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

swan_AmazonFiles/objects/swan_AmazonFile__c/fields/UploadedByName__c.field-meta.xml
<CustomField>
    <fullName>UploadedByName__c</fullName>
    <label>Uploaded By Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

swan_AmazonFiles/objects/swan_AmazonFilesSettings__c/swan_AmazonFilesSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Amazon Files Settings</label>
</CustomObject>

swan_AmazonFiles/objects/swan_AmazonFilesSettings__c/fields/S3BucketARN__c.field-meta.xml
<CustomField>
    <fullName>S3BucketARN__c</fullName>
    <label>S3 Bucket ARN</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

swan_AmazonFiles/classes/swan_AmazonFilesHelper.cls
public without sharing class swan_AmazonFilesHelper {
    
    public static Boolean currentUserHasAccessToFunctionality() {
        return FeatureManagement.checkPermission(swan_AmazonFilesConstants.AMAZON_FILES_VIEW_CUSTOM_PERMISSION) ||
                FeatureManagement.checkPermission(swan_AmazonFilesConstants.AMAZON_FILES_EDIT_CUSTOM_PERMISSION);
    }

    public static Boolean currentUserHasEditAccessToFunctionality() {
        return FeatureManagement.checkPermission(swan_AmazonFilesConstants.AMAZON_FILES_EDIT_CUSTOM_PERMISSION);
    }

    public static Boolean currentUserHasAccessToTheRecord(Id recordId) {
        List<UserRecordAccess> records = [
            SELECT RecordId, HasReadAccess 
            FROM UserRecordAccess 
            WHERE UserId = :UserInfo.getUserId() AND RecordId = :recordId
            LIMIT 1
        ];

        if (records.isEmpty()) return false;

        return records[0].HasReadAccess;
    }

    public static String getCurrentUserInlinePolicyForRecord(Id recordId) {
        swan_AmazonFilesInlinePolicyBuilder policyBuilder = new swan_AmazonFilesInlinePolicyBuilder();
        
        if (FeatureManagement.checkPermission(swan_AmazonFilesConstants.AMAZON_FILES_EDIT_CUSTOM_PERMISSION)) {
            policyBuilder.addStatement(
                swan_AmazonFilesConstants.AWS_EFFECT_ALLOW,
                new List<String> {
                    swan_AmazonFilesConstants.AWS_S3_GET_OBJECT,
                    swan_AmazonFilesConstants.AWS_S3_PUT_OBJECT,
                    swan_AmazonFilesConstants.AWS_S3_DELETE_OBJECT
                },
                swan_AmazonFilesSettings__c.getInstance(swan_AmazonFilesConstants.AWS_ROLE_DEFAULT_CUSTOM_SETTING_NAME).S3BucketARN__c + '/' + String.valueOf(recordId) + '/*'
            );
        } else if (FeatureManagement.checkPermission(swan_AmazonFilesConstants.AMAZON_FILES_VIEW_CUSTOM_PERMISSION)) {
            policyBuilder.addStatement(
                swan_AmazonFilesConstants.AWS_EFFECT_ALLOW,
                new List<String> {
                    swan_AmazonFilesConstants.AWS_S3_GET_OBJECT
                },
                swan_AmazonFilesSettings__c.getInstance(swan_AmazonFilesConstants.AWS_ROLE_DEFAULT_CUSTOM_SETTING_NAME).S3BucketARN__c + '/' + String.valueOf(recordId) + '/*'
            );
        } else {
            return '';
        }


        return policyBuilder.getResultPolicy();
    }

    public static swan_AmazonFile__c createAmazonFileMetadataRecord(String mimeType, String key, String note, Integer size, String fileName) {
        swan_AmazonFile__c newAmazonFile = new swan_AmazonFile__c(
            Key__c = key, 
            MIME__c = mimeType,
            Note__c = note,
            Size__c = size,
            FileName__c = fileName,
            UploadedById__c = UserInfo.getUserId(),
            UploadedByName__c = UserInfo.getName()
        );

        insert newAmazonFile;

        return newAmazonFile;
    }

    public static List<swan_AmazonFile__c> getAmazonFilesByPrefix(String prefix) {
        List<swan_AmazonFile__c> amazonFiles = [
            SELECT Id, Key__c, MIME__c, Note__c, Size__c, FileName__c, UploadedById__c, UploadedByName__c
            FROM swan_AmazonFile__c
            WHERE Key__c LIKE :prefix + '%'
        ];

        return amazonFiles;
    }

    public static void deleteAmazonFile(Id amazonFileId) {
        swan_AmazonFile__c amazonFile = new swan_AmazonFile__c(Id = amazonFileId);
        delete amazonFile;
        
    }

 
}